spring.application.name=auth-service
server.port=${PORT}
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=${URL}
spring.datasource.username=${USER_NAME}
spring.datasource.password=${PASSWORD}
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

#mail sender config
spring.mail.host=smtp.gmail.com
spring.mail.port=${MAIL_PORT}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com

mail.urlFront=${URL_FRONT}