spring.application.name=producto-service
server.port=8084
# === MySQL Config ===
spring.datasource.url=jdbc:mysql://localhost:3306/Producto_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=America/Lima
spring.datasource.username=root
spring.datasource.password=mysql
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# === JPA Config ===
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ? Agrega esto (dialecto explícito)
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
